//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactMgmt.DbManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TagType()
        {
            this.TagValues = new HashSet<TagValue>();
        }
    
        public int TagType_Id { get; set; }
        public string TagName { get; set; }
        public string ValidatorRegEx { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagValue> TagValues { get; set; }
    }
}
